name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 1 * *" # At 09:00 KST, on day 1 of every month
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "certbot.yaml"